# Pin clang version for specific targets
c_compiler_version:              # [osx and arm64]
  - 19                           # [osx and arm64]
  
cxx_compiler_version:              # [osx and arm64]
  - 19                           # [osx and arm64]
