{% set name = "dttlib" %}
{% set version = "0.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://git.ligo.org/cds/software/cr_tools/dttlib/-/archive/{{ version }}/{{ version }}.tar.gz
  sha256: b238051c990312bbddc3ce4288add2f931162ef4f1d47c889264ab68d7eb2f70 

build:
  skip: true  # [not linux]
  error_overlinking: true
  error_overdepending: true
  number: 0
  ignore_run_exports:
    - libclang13
    - zstd

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - make
    - pkg-config
    - ruff
  host:
    - gds-sigp
    - libclang
    - maturin
    - nds2-client
    - pip
    - python
    - rapidjson
    - zstd
  run:
    - python
    - gds-sigp

test:
  requires:
    - pytest
  source_files:
    - test_dttlib.py
  commands:
    - pytest

about:
  home: https://git.ligo.org/cds/software/cr_tools/dttlib
  dev_url: https://git.ligo.org/cds/software/cr_tools/dttlib.git
  license: GPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING-GPL-3
    - THIRDPARTY.yml
  summary: Core library for advanced LIGO frequency domain diagnostics tool

extra:
  recipe-maintainers:
    - evonreis
