schema_version: 1

context:
  name: "dttlib"
  version: "0.9.4"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://git.ligo.org/cds/software/cr_tools/dttlib/-/archive/${{ version }}/${{ version }}.tar.gz
  sha256: bb7b0939d39ad0500b23dedcebd551b375d291361a8a9c4ca998bfe46bcc631c 


build:
  number: 0

  script:
    env:
      JEMALLOC_SYS_WITH_LG_PAGE: ${{ '16' if (aarch64 or ppc64le) else '' }}
      PYTHONIOENCODING: utf-8

requirements:
  build:
    - make
    - pkg-config
    - python
    - cargo-bundle-licenses
    - "${{ compiler('rust') }}"
    - if: not win
      then:
        - "${{ compiler('c') }}" 
        - "${{ stdlib('c') }}"
        - "${{ compiler('cxx') }}"
        - "${{ compiler('rust') }}"
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - maturin

  host:
    - python
    - pip
    - maturin
    - nds2-client
    - rapidjson
    - zstd

  run:
    - python
    - cffi


  ignore_run_exports:
    from_package:
      - cross-python_${{ target_platform }}


tests:
  - requirements:
      run:
        - pytest
    files:
      source:
        - test_dttlib.py
    script:
      - pytest

about:
  homepage: https://git.ligo.org/cds/software/cr_tools/dttlib
  repository: https://git.ligo.org/cds/software/cr_tools/dttlib.git
  license: GPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING-GPL-3
    - THIRDPARTY.yml
  summary: Core library for advanced LIGO frequency domain diagnostics tool

extra:
  recipe-maintainers:
    - evonreis
