# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

schema_version: 1

context:
  name: "dttlib"
  version: "0.5.7"

package:
  name: "${{ name }}"
  version: "${{ version }}"

source:
  url: "https://git.ligo.org/cds/software/cr_tools/dttlib/-/archive/${{ version }}/${{ version }}.tar.gz"
  sha256: f6de9eef8422bc5ce1cac376e4c39a399907dfcc2283248e91153385c1e739a5 

build:
  number: 0
    #script:
    #  env:
    #    JEMALLOC_SYS_WITH_LG_PAGE: ${{ '16' if (aarch64 or ppc64le) else '' }}
    #    PYTHONIOENCODING: utf-8
    #    LIBCLANG_PATH: ${{ PREFIX }}/lib
    #    C_INCLUDE_PATH: ${{ PREFIX }}/include
    #    CPLUS_INCLUDE_PATH: ${{ PREFIX }}/include
    #    LIBRARY_PATH: ${{ PREFIX }}/lib

    #  content:
    #    - "echo PREFIX=x${{ PREFIX }}x"
    #    - "cargo-bundle-licenses --format yaml --output THIRDPARTY.yml"
    #    - "${{ PYTHON }} -m pip install -v --use-pep517 --no-deps --no-build-isolation ."


requirements:
  build:
   - if: not win
     then:
      - ${{ compiler('c') }}
      - ${{ stdlib("c") }}
      - make
      - pkg-config
   - ${{ compiler('rust') }}
   - ${{ compiler('cxx') }}
   - cargo-bundle-licenses
   - if: build_platform != target_platform
     then:
        - cross-python_${{ target_platform }}
        - maturin
   - libclang

  host:
   - gds-sigp
   - libcds
   - libclang
   - maturin
   - nds2-client
   - pip
   - python
   - rapidjson
   - zstd
  run:
    - python
  ignore_run_exports:
    from_package:
      - cross-python_${{ target_platform }}

tests:
  - script:
     - python -m pytest
    requirements:
      run:
        - pytest
    files:
      source:
        - test_dttlib.py
  - python:
     imports:
        - dttlib 
     pip_check: true

about:
  homepage: https://git.ligo.org/cds/software/cr_tools/dttlib
  repository: https://git.ligo.org/cds/software/cr_tools/dttlib.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYING
    - COPYING-GPL-3
    - THIRDPARTY.yml
  summary: Core library for advanced LIGO frequency domain diagnostics tool

extra:
  recipe-maintainers:
    - evonreis
