schema_version: 1

context:
  name: "dttlib"
  version: "0.9.6"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://git.ligo.org/cds/software/cr_tools/dttlib/-/archive/${{ version }}/${{ version }}.tar.gz
  sha256: e02d010c6f6fc96a18390edee04ad36253972e0d7e864de988cc40c5ec3aaa28
  patches:
    - drop_bindgen_complex.patch
    - explicit_nds_link.patch
    - new_nds_client.patch
    - explicit_module_name.patch

build:
  number: 1
    # ignore_run_exports:
    #   - libclang13
    #   - zstd
      # run_exports:
      #   - if: osx
      #     then:
      #       - libosxunwind

  #script_env:
  #  - RUSTFLAGS=-C link-arg=-lunwind  # [osx and arm64]

requirements:
  build:
    - "${{ compiler('c') }}"
    - "${{ stdlib('c') }}"
    - "${{ compiler('cxx') }}"
    - "${{ compiler('rust') }}"
      #   - if: osx
      #     then:
      #       - libosxunwind
    - cargo-bundle-licenses
    - cmake
    - if: not win
      then:
       - make
       - pkg-config
      else:
       - libclang
       - clang
      #- ruff
    - maturin
      #- libpython-static
    - if: build_platform != target_platform
      then:
        - "python"
        - cross-python_${{ target_platform }}
        - libclang
      else:
        - "python"
      
  host:
    - maturin
    - gds-sigp
    - nds2-client
    - pip
    - rapidjson
    - zstd    
    - if: build_platform == target_platform
      then: 
       - python
       - libclang
      else:
       - python 
  run:
    - python
    - gds-sigp

tests:
    - requirements:
        run:
          - pytest
      files:
        source:
          - test_dttlib.py
      script:
        - python -c "import sys; print('*** PYTHON_PATH ***'); print(sys.path)"
        - if: win
          then:
            - dir /s d:\\build\\dttlib*.pyd
        - python -c "import dttlib"
        - pytest

about:
  homepage: https://git.ligo.org/cds/software/cr_tools/dttlib
  repository: https://git.ligo.org/cds/software/cr_tools/dttlib.git
  license: GPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING-GPL-3
    - THIRDPARTY.yml
  summary: Core library for advanced LIGO frequency domain diagnostics tool

extra:
  recipe-maintainers:
    - evonreis
